banner:
  location: classpath:/folderexample/banner.txt
spring:
  datasource:
    url: jdbc:mysql://localhost:8889/mydb?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate: 
      dialect: org.hibernate.dialect.MySQL5Dialect